name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::これはerrorレベルのアノテーション"
      - run: echo "::warning::これはwarningレベルのアノテーション"
      - run: echo "::notice::これはnoticeレベルのアノテーション"