name: Auto Cancel
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # ブランチ名
  cancel-in-progress: true                        # 同一グループのワークフローが実行中ならキャンセル2
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120